name: goofy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_litertlm:
    path: ../flutter_litertlm
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
